### ISSUE TITLE
[BUG]-SourceSelector inputs are not being bridged using the XSIG

### ISSUE THREAD

**Issue by jkdevito** [PepperDash/epi-dsp-tesira#66]
**Describe the bug**
Implemented source selectors and used the 2nd serial join to decode the received XSIG of input names.  When loaded, the XSIG is not populating when Essentials is started or when SIMPL bridge comes online.

**To Reproduce**
1. Create SIMPL program with source selectors
2. Add XSIG to decode the 2nd serial join of the selector

**Expected behavior**
When Essentials starts, the source selector input names should be bridged to SIMPL.  Additionally, if SIMPL restarts, the XSIG should be refreshed.

**Comment by TrevorPayne** [comment]
Resolved in latest release
