### ISSUE TITLE
[BUG]-Faders fail to get min/max levels

### ISSUE THREAD

**Issue by jkdevito** [PepperDash/epi-dsp-tesira#68]
**Describe the bug**
On Essentials boot, faders can fail to get the min/max levels and properly set the scale. 

**Stacktrace**

Include a stack trace of the exception if possible.
```
[dsp1--fader2] Invalid Input Range '-20' for Scaling. Min '0' Max'-20'.
```

**To Reproduce**
1. Load Biamp Tesira plugin
2. Watch for the above message when program is initialized

**Comment by TrevorPayne** [comment]
Im fairly certain this is an issue with the queue.  We had this problem over a year ago and fixed it - I wonder if something changed in tesira firmware that has made this an issue again.

What I'm going to do, I think, is add some config properties to the volume objects that will allow you to explicitly set min/max as a stopgap until I can get the queue fixed.

**Comment by TrevorPayne** [comment]
Resolved in latest release.
