### ISSUE TITLE
[FEATURE]-Answer and Ignore Incoming POTS Calls not working or defined

### ISSUE THREAD

**Issue by cdenig** [PepperDash/epi-dsp-tesira#69]
**Is your feature request related to a problem? Please describe.**
Working with a POTS line using the Dialer.  Most is working well, however, there is no command in the TTP API to reject an incoming POTS call.

On further testing, have found Answer command is not currently functioning for the POTS line.

**Describe the solution you'd like**
Add an Incoming Call Ignore digital join that will take the line Off Hook and then quickly replace On Hook to end the incoming call attempt.  I think this sequence needed due to lack of reject/ignore incoming call command in TTP API.
Update the Answer button to send command to accept incoming POTS call.
https://tesira-help.biamp.com/index.htm#t=System_Control%2FTesira_Text_Protocol%2FAttribute_tables%2FControl_Blocks%2FDialer.html

**Describe alternatives you've considered**
For VoIP lines, there is a Reject incoming call command that should be used.

**Additional context**
Using v2.1.2-hotfix-45 and branch hotfix/stopping-null-ref

**Comment by TrevorPayne** [comment]
This is not going to be automated due to potential differences in POTS systems that have been linked through VOIP bridges.  If you want to reject or answer an incoming call, use the on/off hook options to manage it.
