### ISSUE TITLE
[BUG]-Routers produce SourceSelector error at Init

### ISSUE THREAD

**Issue by cdenig** [PepperDash/epi-dsp-tesira#72]
**Describe the bug**
When Switchers are defined as router type, there is an error when the program/plugin initializes.  Does not occur at later points during runtime.
When program start,s 9x (corresponding to number of outputs defined) of the following errors are produced.  Errors occur after Essentials Load Complete message is produced.  No Instance Tag errors exist.  All router outputs are real and defined in DSP program.

**Stacktrace**
Error: SimplSharpPro[App01] # 2022-11-02 16:51:06 # App 1:[dsp1-plugin] Error From DSP: '-ERR 'sourceSelection' is not supported by RouterInterface::Attributes'

**To Reproduce**
Load Essentials config with following switcher control blocks:
```
"switcherControlBlocks" : {
						"SwitcherControl01" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 1,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 1
						},
						"SwitcherControl02" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 2,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 2
						},
						"SwitcherControl03" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 3,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 3
						},
						"SwitcherControl04" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 4,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 4
						},
						"SwitcherControl05" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 5,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 5
						},
						"SwitcherControl06" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 6,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 6
						},
						"SwitcherControl07" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 7,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 7
						},
						"SwitcherControl08" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 8,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 8
						},
						"SwitcherControl09" : {
							"enabled" : true,
							"label" : "DSP Switcher",
							"index1" : 9,
							"switcherInstanceTag" : "router",
							"type": "router",
							"bridgeIndex" : 9
						}
					}
```

**Expected behavior**
Expect that initialization of a router-type switcher would not use a Source Selector command

**Screenshots**

**Additional context**

**Comment by cdenig** [comment]
@TrevorPayne this continues to be an issue with latest versions.

I would expect a router-type selector object to poll all output indices for current routes at initialization

**Comment by cdenig** [comment]
![image](https://user-images.githubusercontent.com/86131648/218111845-7fde9515-3fe4-46e7-9a4c-583d285db269.png)

**Comment by TrevorPayne** [comment]
Routers are not source selectors and aren't subscribable.

We can investigate polling the individual outputs, but you still have to build one block per output in the current framework.

I'm open to changing it in the next version (which is pending), but  I believe we have an explicit poll signal for this block.

If we don't, we should add it.  We can also investigate an initial poll, but I thought I was doing that already.

On Feb 10, 2023 8:07 AM, cdenig ***@***.***> wrote:

[image]<https://user-images.githubusercontent.com/86131648/218111845-7fde9515-3fe4-46e7-9a4c-583d285db269.png>
