### ISSUE TITLE
[FEATURE]-Polling for router-type Switcher

### ISSUE THREAD

**Issue by cdenig** [PepperDash/epi-dsp-tesira#73]
**Is your feature request related to a problem? Please describe.**
When using a "router" as a switcher type, add support for polling.  Currently have a system with Crestron and Biamp-native (TEC-X) controls and Crestron needs to support switching and source sync from both platforms.

**Describe the solution you'd like**
When the switcher type is a "router", send a "get input" poll string every XX seconds.  Bonus points for configurable interval AND manual poll trigger support from bridge.

**Describe alternatives you've considered**
Ask DSP engineer to change a single router into many separate source selector blocks.  This would grossly over-complicate the DSP program.

**Additional context**
NA

**Comment by cdenig** [comment]
@TrevorPayne I added this FR a while back.  Looks like might tie in with [Issue 72](https://github.com/PepperDash/epi-dsp-tesira/issues/72)

**Comment by cdenig** [comment]
An individual Poll accessible via the Bridge would be great.  Could manage cycle timing from SIMPL as well as custom polling (like following preset recalls known to affect Routers)

**Comment by TrevorPayne** [comment]
Because it's being defined as a source selector in the config, and it's not.

Add a type property with the value "router"

This works, it just needs to be better documented.

On Feb 10, 2023 8:42 AM, cdenig ***@***.***> wrote:

@TrevorPayne<https://github.com/TrevorPayne> I added this FR a while back. Looks like might tie in with Issue 72<https://github.com/PepperDash/epi-dsp-tesira/issues/72>

**Comment by cdenig** [comment]
SwitcherControlXX are all defined as "type": "router"

Looks like the Subscribe() method for Switcher only supports subscribable sourceSelectors.  Looks like there is no check for switcher Type at this point.  Possible it is done elsewhere?
How well does the CrosspointState function? Possible its polling logic could serve as a model for control points that are not subscribable?

Attached is essentials config (extension changed to allow attach) with switcher control blocks starting on Line 368.
[nyu01301_t04-subcellarAudio-p01-configurationFile-essentials.txt](https://github.com/PepperDash/epi-dsp-tesira/files/10709801/nyu01301_t04-subcellarAudio-p01-configurationFile-essentials.txt)

**Comment by TrevorPayne** [comment]
We control this device just fine - Andrew K used it for a 62 output router block this week.

We just don't have a check to prevent the subscribe from happening.  It's benign, albeit annoying, I believe.

You're welcome to add the check in the subscribe method and push up a PR ;)

On Feb 10, 2023 11:34 AM, cdenig ***@***.***> wrote:

SwitcherControlXX are all defined as "type": "router"

Looks like the Subscribe() method for Switcher only supports subscribable sourceSelectors. Looks like there is no check for switcher Type at this point. Possible it is done elsewhere?
How well does the CrosspointState function? Possible its polling logic could serve as a model for control points that are not subscribable?

Attached is essentials config (extension changed to allow attach) with switcher control blocks starting on Line 368.
nyu01301_t04-subcellarAudio-p01-configurationFile-essentials.txt<https://github.com/PepperDash/epi-dsp-tesira/files/10709801/nyu01301_t04-subcellarAudio-p01-configurationFile-essentials.txt>
