### ISSUE TITLE
[BUG]-Standalone State devices failing to map to bridge

### ISSUE THREAD

**Issue by cdenig** [PepperDash/epi-dsp-tesira#77]
**Describe the bug**
When attempting to add a standalone state device to a bridge, the following PostActivation error is generated and bridge is not created.

**Stacktrace**

Include a stack trace of the exception if possible.
```
App 1:[dsp-custom-bridge] ERROR: Device dsp-custom-bridge PostActivation failure: Object must implement IConvertible.
```

**To Reproduce**
1. create a state device
2. Create a custom bridge of type eiscApiAdvanced
3. Add state device to bridge _{"deviceKey":"dsp--state1" ,"joinStart": 1001}_
5. Restart Essentials and see error above

**Expected behavior**
One would expect to be able to add standalone State devices without error

**Configuration Snippets**
```
"stateControlBlocks" : {
            "state1" : {
              "enabled" : true,
              "label" : "Wall AB Set",
              "stateInstanceTag" : "WALL",
              "index" : 1,
              "bridgeIndex" : 1
            }
```

```
{ "key": "dsp-custom-bridge",
        "uid": 26,
        "name": "Custom Dsp Bridge",
        "group": "api",
        "type": "eiscApiAdvanced",
        "properties": {
          "control": {
            "tcpSshProperties": { "address": "127.0.0.2", "port": 0 },
            "ipid": "aa",
            "method": "ipidTcp"
          },
          "devices": [
             {"deviceKey":"dsp--state1" ,"joinStart": 1001}
          ]
        }
      }
```

**Comment by TrevorPayne** [comment]
Resolved in latest release
